### ISSUE TITLE
Segfault on Linux when matplotlib.rcParams["agg.path.chunksize"] = 1000 enabled

### ISSUE THREAD

**Issue by jimbo1qaz** [anntzer/mplcairo#13]
`double free or corruption (!prev)`

I use matplotlib to render a series of video frames. I tried but failed to create a simplified example.

## Test case?

I think I've found the single input which causes Cairo to fail (1764 lines): https://gist.github.com/jimbo1qaz/a4e6d682343ac991425e522dd5667262#file-data-py

I was only able to make my full program crash, not any smaller test case.

agg.path.chunksize is 1000. Removing or changing value of parameter seems to make bug not happen. Changing render resolution (originally 1280x720) causes bug to disappear or symptoms to change (`corrupted size vs. prev_size`, `free(): invalid next size (normal)`...). But given a fixed environment, bug happens on the same (or similar) frame of input every time.

## gdb backtrace

https://gist.github.com/jimbo1qaz/a4e6d682343ac991425e522dd5667262#file-0-gdb-bt

## valgrind python -m corrscope

https://gist.github.com/jimbo1qaz/a4e6d682343ac991425e522dd5667262

wow, valgrind is slow. FPS = 2.5168215886315983

## Version

Kubuntu 18.04, Python 3.7.2 compiled via pyenv.

```
apt show libcairo2
Package: libcairo2
Version: 1.15.10-2

pip show mplcairo
Name: mplcairo
Version: 0.1
```
bug still happens on mplcairo-0.1.post63+g17c19d9

Do you think it's an upstream/libcairo bug?

**Comment by anntzer** [comment]
Is the program available somewhere for me to try?
Can you try saving cairoscript outputs as documented in https://github.com/anntzer/mplcairo#cairo-script-output to document the calls to the cairo interface?

**Comment by jimbo1qaz** [comment]
Program: https://github.com/jimbo1qaz/corrscope/tree/cairo
Config: [mplcairo-bug.zip](https://github.com/anntzer/mplcairo/files/2798819/mplcairo-bug.zip)

To install program, run shell commands:

```sh
poetry install
cd path/to/mplcairo-bug/
python -m corrscope file.yaml -p
```

Or omit cd and supply absolute path to mplcairo-bug.zip/file.yaml.

-------

Do I set MPLCAIRO_SCRIPT_SURFACE to vector or raster? I normally call `fig.canvas.draw()` which is sufficient to crash the program, even when `fig.canvas.get_renderer()._get_buffer()` is commented out.

**Comment by anntzer** [comment]
With poetry 0.12.11 and the repo cloned at the HEAD of the cairo branch, I get
```
$ poetry install
Installing dependencies from lock file


Package operations: 29 installs, 1 update, 0 removals

  - Installing altgraph (0.16.1)
  <elided>
  - Installing corrscope (0.2.0-pre)
                                            
[PermissionError]            
[Errno 13] Permission denied: '/tmp/corrscope/setup.py'  
                                            
install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```
Well, there's no setup.py in the repo indeed.  Dunno if poetry wants one or something.

(As a side note, I would suggest providing a setup.py for your package; I (strictly personally) find it annoying to have to use a nonstandard installer.  But let's not derail from the main issue.)

**Comment by jimbo1qaz** [comment]
There is a .whl and a .tar.gz with setup.py:

[corrscope.zip](https://github.com/anntzer/mplcairo/files/2799570/corrscope.zip)

**Comment by anntzer** [comment]
Thanks, I can now reproduce the failure (even with mplcairo master).
I'll investigate, but no guarantees on the schedule as this may be extremely deep just as this may be something trivial...

**Comment by anntzer** [comment]
This is a bug in cairo indeed, specifically https://gitlab.freedesktop.org/cairo/cairo/issues/44.  Applying
```
diff --git i/src/cairo-tor22-scan-converter.c w/src/cairo-tor22-scan-converter.c
index bf44742b0..202453b4d 100644
--- i/src/cairo-tor22-scan-converter.c
+++ w/src/cairo-tor22-scan-converter.c
@@ -1291,8 +1291,8 @@ glitter_scan_converter_reset(
     converter->xmin = 0; converter->xmax = 0;
     converter->ymin = 0; converter->ymax = 0;
 
-    if (xmax - xmin > ARRAY_LENGTH(converter->spans_embedded)) {
-       converter->spans = _cairo_malloc_ab (xmax - xmin,
+    if (xmax - xmin + 1 > ARRAY_LENGTH(converter->spans_embedded)) {
+       converter->spans = _cairo_malloc_ab (xmax - xmin + 1,
                                             sizeof (cairo_half_open_span_t));
        if (unlikely (converter->spans == NULL))
            return _cairo_error (CAIRO_STATUS_NO_MEMORY);
```
to the cairo 1.16.0 (for example) source tree (the patch is implied by the comments on that thread) and linking against that cairo fixes the issue.

Unfortunately, I don't think there's anything I can do on my side? :/

**Comment by jimbo1qaz** [comment]
Does not setting agg.path.chunksize completely avoid this bug, or could it still crash?

**Comment by jimbo1qaz** [comment]
Does `dict.__setitem__(matplotlib.rcParams, "lines.antialiased", False)` or `antialias_t.DEFAULT` prevent this bug from occurring? The original post claims `CAIRO_ANTIALIAS_BEST` doesn't crash. (I'm probably not switching to mplcairo if I can't ensure it's fully stable, which is a shame considering how much faster non-AA is compared to Agg non-AA.)

(Are you OK with answering my questions, or would you prefer i stop asking?)

**Comment by anntzer** [comment]
Grepping through the code suggests that the buggy tor22 scan converter is only used for ANTIALIAS_FAST:
```
} else {
	const cairo_rectangle_int_t *r = &extents->unbounded;

	if (antialias == CAIRO_ANTIALIAS_FAST) {
	    converter = _cairo_tor22_scan_converter_create (r->x, r->y,
							    r->x + r->width,
							    r->y + r->height,
							    fill_rule, antialias);
	    status = _cairo_tor22_scan_converter_add_polygon (converter, polygon);
	} else if (antialias == CAIRO_ANTIALIAS_NONE) {
	    converter = _cairo_mono_scan_converter_create (r->x, r->y,
							   r->x + r->width,
							   r->y + r->height,
							   fill_rule);
	    status = _cairo_mono_scan_converter_add_polygon (converter, polygon);
	} else {
	    converter = _cairo_tor_scan_converter_create (r->x, r->y,
							  r->x + r->width,
							  r->y + r->height,
							  fill_rule, antialias);
	    status = _cairo_tor_scan_converter_add_polygon (converter, polygon);
	}
}
```
(in cairo-spans-compositor.c::composite_polygon), so you're probably(?) safe with other forms of antialiasing (see https://github.com/anntzer/mplcairo#antialiasing for how mplcairo sets the aliasing by default; I may change that now that I know this problem... reopening the issue for that).

I'm happy to help you of course :)

**Comment by anntzer** [comment]
Added a note mentioning the problem in the README, but decided against changing the default both because it would be costly from a performance POV and because I had actually never hit that issue after one year of using mplcairo as my sole backend, and still don't have a good understanding of what exactly triggers it.
